package ilenreste.unpeu.recettesback.services.media;

import ilenreste.unpeu.recettesback.configuration.MediaProperties;
import lombok.extern.log4j.Log4j2;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Optional;

/**
 * Stores image bytes under a configured root directory on the local filesystem.
 */
@Log4j2
@Service
public class FilesystemMediaStorageService implements MediaStorageService {

    private final Path root;

    public FilesystemMediaStorageService(MediaProperties properties) {
        this.root = properties.storagePath().toAbsolutePath().normalize();
        try {
            Files.createDirectories(root);
        } catch (IOException exception) {
            // Fail at startup rather than on the first upload: a misconfigured or unwritable
            // storage path is an operator error, and finding out when a user tries to add a photo
            // means the failure surfaces as a 500 to them instead of a red boot log to you.
            throw new IllegalStateException("Media storage root is not usable: " + root, exception);
        }
        if (!Files.isWritable(root)) {
            throw new IllegalStateException("Media storage root is not writable: " + root);
        }
        log.info("Media storage root is {}", root);
    }

    @Override
    public void store(String storageKey, byte[] content) {
        Path target = resolveWithinRoot(storageKey);
        try {
            Files.createDirectories(target.getParent());
            // Write to a sibling temp file and move it into place, so a crash or a full disk
            // halfway through cannot leave a truncated file that later reads serve as a valid
            // image. A sibling (not the system temp dir) keeps the move on one filesystem, which
            // is what lets it be atomic.
            Path temporary = Files.createTempFile(target.getParent(), ".upload-", ".tmp");
            try {
                Files.write(temporary, content);
                moveIntoPlace(temporary, target);
            } catch (IOException exception) {
                Files.deleteIfExists(temporary);
                throw exception;
            }
        } catch (IOException exception) {
            throw new UncheckedIOException("Could not store media under " + storageKey, exception);
        }
        log.debug("Stored {} bytes under {}", content.length, storageKey);
    }

    @Override
    public Optional<Resource> load(String storageKey) {
        Path target;
        try {
            target = resolveWithinRoot(storageKey);
        } catch (IllegalArgumentException exception) {   // InvalidPathException is one of these
            // A key that escapes the root can only come from a corrupted row or a bug, never from
            // a request - but answering "not found" is the right outcome either way.
            log.error("Refusing to read a media key that does not resolve inside the storage root", exception);
            return Optional.empty();
        }
        if (!Files.isRegularFile(target)) {
            log.warn("Media row points at {}, which is not on disk", storageKey);
            return Optional.empty();
        }
        return Optional.of(new FileSystemResource(target));
    }

    @Override
    public void delete(String storageKey) {
        try {
            Files.deleteIfExists(resolveWithinRoot(storageKey));
            log.debug("Deleted media file {}", storageKey);
        } catch (IOException | IllegalArgumentException exception) {
            // Best effort: this runs while unwinding a failed upload, and failing here would
            // replace the real error with a less useful one. A file left behind is an orphan,
            // which is a disk-space problem, not a correctness one.
            log.error("Could not delete media file {}", storageKey, exception);
        }
    }

    /**
     * Defence in depth against path traversal.
     * <p>
     * Storage keys are generated by the server from a UUID and are never parsed
     * from a request, so nothing should ever reach here with {@code ../} in it.
     * This asserts it anyway, because the cost is one comparison and the failure
     * mode it prevents is reading or overwriting arbitrary files as the
     * application user.
     */
    private Path resolveWithinRoot(String storageKey) {
        Path resolved = root.resolve(storageKey).normalize();
        if (!resolved.startsWith(root)) {
            throw new IllegalArgumentException("Storage key escapes the storage root: " + storageKey);
        }
        return resolved;
    }

    private void moveIntoPlace(Path temporary, Path target) throws IOException {
        try {
            Files.move(temporary, target, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
        } catch (AtomicMoveNotSupportedException exception) {
            // Some filesystems cannot do it; a plain move is still better than writing in place.
            log.warn("Atomic move unavailable on this filesystem, falling back to a plain move");
            Files.move(temporary, target, StandardCopyOption.REPLACE_EXISTING);
        }
    }
}
