spring.application.name=recettes-back
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
#UPDATE PASSWORD METHOD
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.session.jdbc.initialize-schema=always
spring.security.filter.order=0