package ilenreste.unpeu.recettesback.entities.media;

import ilenreste.unpeu.recettesback.entities.users.UserEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

/**
 * Metadata for one stored image. The bytes live on the filesystem behind
 * {@code MediaStorageService}; this row only points at them.
 * <p>
 * <strong>Every column here describes the file we stored, never the file that
 * was uploaded.</strong> That is obvious for {@code contentType} and
 * {@code sizeBytes} and easy to get wrong for {@code width}/{@code height},
 * because the pipeline reads dimensions twice: once from the header to reject
 * decompression bombs before decoding, and once from the image actually written
 * after downscaling and EXIF rotation. The header values are the natural
 * mistake to reuse, and they make a 4032x3024 phone photo stored at 2000x1500
 * record 4032x3024 - defeating the column's whole purpose, since the frontend
 * then reserves a box at twice the real pixel size.
 * <p>
 * Media rows are <strong>immutable</strong>: an edited picture is a new upload
 * with a new id, never a rewrite. That is what makes the year-long
 * {@code immutable} cache header on {@code GET /media/{id}} safe, and it is why
 * this entity does not extend {@code AuditableEntity} - {@code updatedAt} and
 * {@code updatedBy} would be dead columns.
 * <p>
 * It therefore declares its own two audit fields and carries
 * {@link EntityListeners} <strong>itself</strong>. Forgetting that listener is
 * silent at compile time and fatal at runtime: {@code created_at} is
 * {@code NOT NULL} and every {@code POST /media} would die on the constraint.
 */
@Getter
@Setter
@Entity
@EntityListeners(AuditingEntityListener.class)
@Table(name = "media", indexes = {
        // Serves the orphan sweep's created_at half. The three NOT EXISTS probes it also needs are
        // indexed from the referencing tables, which arrive with the recipes entities.
        @Index(name = "idx_media_created_at", columnList = "created_at")
})
public class MediaEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * Relative path under the storage root, e.g. {@code ab/cd/<uuid>.jpg}. An
     * opaque string as far as the rest of the application is concerned, which is
     * what lets a future S3 backend reuse it as an object key with no schema
     * change. Always generated by the server, never parsed from a request.
     */
    @Column(nullable = false, unique = true)
    private String storageKey;

    /**
     * Key of the downscaled variant served to list pages. Stored rather than
     * derived from {@link #storageKey}: deriving would impose a naming
     * convention on a string documented as opaque, and would break every
     * existing row the day that convention changes.
     */
    @Column(nullable = false, unique = true)
    private String thumbnailStorageKey;

    /** Decided by our re-encoder. Never the client's declared content type. */
    @Column(nullable = false)
    private String contentType;

    @Column(nullable = false)
    private int width;

    @Column(nullable = false)
    private int height;

    @Column(nullable = false)
    private long sizeBytes;

    /**
     * Of the stored (re-encoded) bytes, for integrity checking and orphan
     * auditing. Deliberately <strong>not</strong> unique: deduplicating would
     * make two recipes share one row, and deleting one recipe must then not
     * delete the other's picture - refcounting that is real complexity for a
     * saving that does not matter at this scale.
     */
    @Column(nullable = false, length = 64)
    private String checksumSha256;

    /** Who to attribute an abuse report to, and the basis for a future quota. */
    @CreatedBy
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "uploaded_by_id", updatable = false)
    private UserEntity uploadedBy;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;
}
